name: compilation_ex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  i_message: # Gets compiled in both AOT and JIT
    path: ./i_message
  prod_message: # Gets compiled during AOT
    path: ./prod_message
  test_message: # Gets compiled during JIT
    path: ./test_message

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # package_exclusions:
  #   test_message:
  #     - aot
  #   prod_message:
  #     - jit
